config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users

  resources :adults

  resources :seniors

  resources :youths

  resources :workouts

  resources :blogs

  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :User, optional: true

  validates :article, presence: true
  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :workouts
  has_many :blogs
  validates :email, uniqueness: true
  validates :name, :email, :password, presence: true

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end

end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :User, optional: true
end

app/controllers/adults_controller.rb
class AdultsController < ApplicationController
  before_action :require_login


  def index

  end

  def new
    @adult = Adult.new
  end

  def create
    @adult = Adult.create(adult_params)
    if @adult.save
      redirect_to users_path
    end
  end

  def show
    @adult = Adult.find_by_id(params[:id])
  end

  private

  def adult_params
    params.require(:adult).permit(:adult_title, :link, :description)
  end

  # def create
  #   @blog = Blog.create(blog_params)
  #   if @blog.valid?
  #     @user = User.find_by_id(session[:user_id])
  #     @user.blogs << @blog
  #     redirect_to user_path(@user)
  #   else
  #     redirect_to new_blog_path
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :require_login, except: [:show]

  def show
    @blog = Blog.find_by_id(params[:id])
    @user = User.find_by_id(@post.user_id)
  end

  def new
    if session[:user_id] == nil
      flash[:error] = "You must be logged in to create a blog post."
      redirect_to user_path(session[:user_id])
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.create(blog_params)
    if @blog.valid?
      @user = User.fin_by_id(session[:user_id])
      @user.blogs << @blog
    else
      flash[:error] = "#{@blog.errors.full_messages.join(", ")}"
      redirect_to new_blog_path
  end

  def edit
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @blog.update(blog_params)
    redirect_to blog_path(@blog)
  end

  def destory
    @blog.destroy
    redirect_to user_path(session[:user_id])
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def user_match?
    @blog = Blog.find_by_id(params[:id])
    if session[:user_id] != @blog.user_id
      redirect_to root_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :require_login
  before_action :user_match?, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end
  def show
    @blog = Blog.find_by_id(params[:id])
    @user = User.find_by_id(@blog.user_id)
  end

  def new
      @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
    if @blog.valid?
      @user = User.find_by_id(session[:user_id])
      @user.blogs << @blog
      redirect_to user_path(@user)
    else
      redirect_to new_blog_path
    end
  end

  def edit
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @blog.update(blog_params)
    redirect_to blog_path(@blog)
  end

  def destory
    @blog.destroy
    redirect_to user_path(session[:user_id])
  end

  private
  def blog_params
    params.require(:blog).permit(:article, :content)
  end

  def user_match?
    @blog = Blog.find_by_id(params[:id])
    if session[:user_id] != @blog.user_id
      redirect_to root_path
    end
  end
end

app/controllers/seniors_controller.rb
class SeniorsController < ApplicationController
  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
      @user = User.confirm(user_params)
      if @user
        login(@user)
        redirect_to user_path(@user)
      else
        flash[:error] = "Incorrect email or password."
        redirect_to login_path
      end
  end

  def destroy
    logout
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update]

  def index
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
      if @user.valid?
        login(@user)
        redirect_to @user
      else
        flash[:error] = "#{@user.errors.full_messages.join(", ")}"
        redirect_to new_user_path
      end
  end

  def show
    @user = User.find_by_id(params[:id])
    @blogs = @user.blogs
  end

  def edit
    @user = User.find_by_id(session[:user_id])
  end

  def update
    @user = User.find_by_id(session[:user_id])
    @user.update(user_params)
    @user.save(validate: false)
    redirect_to user_path(@user.id)
  end

 def user_params
   params.require(:user).permit(:name, :email, :password, :age, :current_weight, :goal_weight, :nutrition_goals, :stretch_goals, :strength_goals, :cardio_goals)
 end


end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :require_login
  before_action :user_match?, only: [:edit, :update, :destroy]

  def index
    @workouts = Workout.all
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.create(workout_params)
    if @workout.save
      redirect_to users_path
    end
  end

  def show
    @workout = Workout.find_by_id(params[:id])
    @user = User.find_by_id(@workout.user_id)
  end
  private

  def workout_params
    params.require(:workout).permit(:workout_type, :exercises, :experience)
  end

end

app/controllers/youths_controller.rb
class YouthsController < ApplicationController
  def index

  end
end

app/helpers/adult_nutrition_helper.rb
module AdultNutritionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/senior_nutrition_helper.rb
module SeniorNutritionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def require_login
    redirect_to root_path and return if session[:user_id] == nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/helpers/youth_nutrition_helper.rb
module YouthNutritionHelper
end

app/views/adults/index.html.erb
<div class="container">
  <h1>This is the adult fitness & nurition page</h1>

  <button><%= link_to "New Article", new_adult_path %></button>
</div>

app/views/adults/new.html.erb
<div class="container">
  <h1>Add Article</h1>
  <%= form_for @adult do |u| %>
    <div>
      <%= u.text_field :adult_title, placeholder: 'Title' %>
    </div>
    <div>
      <%= u.text_field :link, placeholder: 'link' %>
    </div>
    <div>
      <%= u.text_area :description, placeholder: 'Description' %>
    </div>
    <%= u.submit %>
  <% end %>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <h2>The Stretch Blog</h2>
  <% @blogs.each do |blog| %>
  <div>
    <h4><%= blog.article %></h4>
    <p><%= blog.content %></p>
  </div>
  <hr>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <h1>Create A New Blog Post</h1>
  <%= form_for @blog do |u| %>
    <div>
      <%= u.text_field :article, placeholder: "Title" %>
    </div>
    <div>
      <%= u.text_area :content, placeholder: "Content" %>
    </div>
    <button><%= u.submit %></button>
  <% end %>
</div>

app/views/seniors/index.html.erb
<div class="container">
  <h1>This is the senior fitness & nutrition page</h1>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>Edit Profile</h1>
  <%= form_for @user do |u| %>
    <div>
      <%= u.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
      <%= u.number_field :age, placeholder: 'Age' %>
    </div>
    <div>
      <%= u.number_field :current_weight, placeholder: 'Current Weight' %>
    </div>
    <div>
      <%=u.number_field :goal_weight, placeholder: 'Goal Weight' %>
    </div>
    <div>
      <%= u.text_field :strength_goals, placeholder: 'Strength Goals' %>
    </div>
    <div>
      <%= u.text_field :cardio_goals, placeholder: 'Cardio Goals' %>
    </div>
    <div>
      <%= u.text_field :nutrition_goals,
      placeholder: 'Nutrition Goals' %>
    </div>
    <div>
      <%= u.text_field :stretch_goals, placeholder: 'Flexibility Goals' %>
    </div>
    <%= u.submit 'Save' %>
  <% end %>
  <%= link_to 'Profile', user_path(@user) %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Welcome to Stretch Fitness & Nutrition</h1>

  <h3><%= link_to "Sign Up", new_user_path %></h3>
  <h3><%= link_to "New Blog Post", new_blog_path%></h3>
  <br>

  <div>
    <p>Fitness & Nutrition Offerings</p>
    <ul>
      <li><%= link_to "Adults", adults_path %></li>
      <li><%= link_to "Seniors", seniors_path %></li>
      <li><%= link_to "Youth", youths_path %></li>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Create Profile</h1>
  <%= form_for @user do |u| %>
    <div>
      <%= u.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
      <%= u.text_field :email, placeholder: 'Email' %>
    </div>
    <div>
      <%= u.number_field :age, placeholder: 'Age' %>
    </div>
    <div>
      <%= u.number_field :current_weight, placeholder: 'Current Weight' %>
    </div>
    <div>
      <%=u.number_field :goal_weight, placeholder: 'Goal Weight' %>
    </div>
    <div>
      <%= u.text_field :strength_goals, placeholder: 'Strength Goals' %>
    </div>
    <div>
      <%= u.text_field :cardio_goals, placeholder: 'Cardio Goals' %>
    </div>
    <div>
      <%= u.text_field :nutrition_goals,
      placeholder: 'Nutrition Goals' %>
    </div>
    <div>
      <%= u.text_field :stretch_goals, placeholder: 'Flexibility Goals' %>
    </div>
    <div>
      <%= u.password_field :password, placeholder: 'Password' %>
    </div>
    <%= u.submit 'Sign Up'%>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>Name: <%= @user.name %></h1>
  <h1>Age: <%= @user.age %></h1>
  <h1>Current Weight: <%= @user.current_weight %></h1>
  <h1>Goal Weight: <%= @user.goal_weight %></h1>
  <h1>Pounds to Loose: <%= @user.goal_weight - @user.current_weight %>
  <h1>Nutrition Goals: <%= @user.nutrition_goals %></h1>
  <h1> Flexibility Goals: <%= @user.stretch_goals %></h1>
  <h1>Strength Goals: <%= @user.strength_goals %></h1>
  <h1> Cardio Goals: <%= @user.cardio_goals %></h1>


  <button><%= link_to "Add Workout", new_workout_path %></button>
  <button><%= link_to "Workouts", workout_path %></button>
  <button><%= link_to "Edit Profile", edit_user_path %></button>

  <br>

</div>

app/views/workouts/index.html.erb
<div class="container">
  <% @workouts.each do |workout| %>
    <h3><%=workout.workout_type%></h3>
    <h6><%=workout.exercises%></h6>
    <p><%=workout.experience%></p>
  <% end %>
</div>

app/views/workouts/new.html.erb
<div class="container">
  <h1>Add Workout</h1>
  <%= form_for @workout do |u| %>
    <div>
      <%= u.text_field :workout_type, placeholder: 'Weights, Running' %>
    </div>
    <div>
      <%= u.text_field :exercises, placeholder: 'Exercises, Distance Run' %>
    </div>
    <div>
      <%= u.text_area :experience, placeholder: 'How did the workout feel?' %>
    </div>
    <%= u.submit %>
  <% end %>
</div>

app/views/workouts/show.html.erb
<div class="container">
  <% @workouts.each do |w| %>
    <%if (@current_user.id === w.user_id)
      <%= <h3>w.workout_type</h3> %>
      <%= <h6>w.exercises</h6> %>
      <%= <p>w.experience</p> %>
    <% end %>
    <% end %>
</div>
<!-- <% @characters.each do |c| %>
         <% if (current_user.id === c.user_id) %>
           <div class="col s12 m6 l6 cards-container">
             <div class="card grid-item">
                 <div class="card-image">
                   <img src="<%= c.image %>">
                 </div>
                 <div class="card-content">
                   <span class="card-title"><%= c.name %></span>
                   <p>Age: <%= c.age %></p>
                   <p>Level: <%= c.level %></p>
                   <p>Experience: <%= c.xp %></p>
                   <p>Class: <%= c.class_name %></p>
                 </div>
                 <div class="card-action">
                 <%=link_to "Character Details", character_path(c.id) %>
               </div>
             </div>
           </div>
         <% end %>
       <% end %> -->

app/views/youths/index.html.erb
<div class="container">
  <h1>This is the youth fitness & nutrition page</h1>
</div>